---
# usage:
#   include_role:
#     name: criecm.apache
#     tasks_from: vhost.yml
#   vars:
#     vhost: '{{  site }}'

- name: os vars
  include_vars: '{{ ansible_os_family }}.yml'

- name: full role if needed
  include_role:
    name: criecm.apache
  vars:
    sites: [ '{{ vhost }}']
  when: '"criecm" not in ansible_local or "apache" not in ansible_local.criecm or ansible_local.criecm.apache.version | int < apache_role_version | int'
  register: fulldone

- name: apache sites
  include_tasks: site.yml
  with_items:
    - '{{ vhost }}'
  loop_control:
    loop_var: onesite
  when: not fulldone.changed
