---
# usage:
#   include_role:
#     name: criecm.apache
#     tasks_from: vhost.yml
#   vars:
#     vhost: '{{  site }}'

- name: os vars
  include_vars: '{{ ansible_os_family }}.yml'

- name: site vars
  include_vars: site.yml

- name: apache sites
  include_tasks: site.yml
  with_items:
    - '{{ vhost }}'
  loop_control:
    loop_var: onesite
