---
siteconf_locations:
  - '{{ playbook_dir }}/templates/{{ site.id }}/apache/{{ site.id }}.conf.j2'
  - '{{ playbook_dir }}/files/{{ site.id }}/apache/{{ site.id }}.conf'
  - templates/site.conf.j2

include_locations:
  - '{{ item }}.j2'
  - '{{ item }}'
  - '{{ playbook_dir }}/templates/{{ site.id }}/apache/{{ item }}.j2'
  - '{{ playbook_dir }}/files/{{ site.id }}/apache/{{ item }}'
  - 'templates/apache/{{ item }}.j2'
  - '{{ playbook_dir }}/files/apache/{{ item }}'

site_port: '{% if "tls_cert" in onesite and onesite.tls_cert != "" %}443{% else %}80{% endif %}'

apache_rewrite_site_config: '{{ override_site_config | default(apache_rewrite_config) }}'

# site par defaut
default_site:
  id: default
  name: ''
  aliases: []
  apache_includes: []
  apache_directives: []
  backends: []
  rootdir: '{% if "rootsrc" in onesite or "gitroot" in onesite %}{{ apache_rootbase }}/{{ onesite.id }}{% endif %}'
  rootsrc: ''
  gitroot: ''
  group: '{{ www_group }}'
  user: '{{ www_user }}'
  grwfiles: []
  grwdirs: []
  tls: False
  tls_redir: False
  listen: '{{ server_listen_ips | map("regex_replace","$",":"+site_port) | list }}'
  default_index: 'index.html'
  status_path: '/apache-status'
  prefixes:
    - path: /
      allow_from_nets: []
  fcgi_status_path: ''
